export const DEFAULT_PRODUCTS = [
    { "id": "prod-001", "model": "DR-X500", "category": "medical", "image": "/Assets/xray-system.png", "isNew": true, "name": { "en": "Digital X-Ray System", "ru": "Цифровая рентгеновская система", "uz": "Raqamli rentgen tizimi" }, "description": { "en": "High-resolution digital radiography with wireless flat panel detector", "ru": "Цифровая рентгенография высокого разрешения", "uz": "Simsiz tekis panel detektori bilan yuqori aniqlikdagi raqamli rentgenografiya" }, "price": "Contact for Quote" },
    { "id": "prod-002", "model": "CT-1000", "category": "medical", "image": "/Assets/ct-scanner.png", "isNew": false, "name": { "en": "CT Scanner", "ru": "Компьютерный томограф", "uz": "Kompyuter tomografiya" }, "description": { "en": "64-slice computed tomography scanner", "ru": "64-срезовый компьютерный томограф", "uz": "64 qatlamli kompyuter tomografiya" }, "price": "Contact for Quote" },
    { "id": "prod-003", "model": "MRI-3000", "category": "medical", "image": "/Assets/mri-scanner.png", "isNew": true, "name": { "en": "MRI Scanner", "ru": "МРТ сканер", "uz": "MRT skaneri" }, "description": { "en": "1.5T Magnetic Resonance Imaging system", "ru": "МРТ система 1.5 Тесла", "uz": "1.5T MRT tizimi" }, "price": "Contact for Quote" },
    { "id": "prod-004", "model": "ECG-500", "category": "medical", "image": "/Assets/ecg-machine.png", "isNew": false, "name": { "en": "ECG Machine", "ru": "ЭКГ аппарат", "uz": "EKG apparati" }, "description": { "en": "12-lead electrocardiograph with touchscreen", "ru": "12-канальный электрокардиограф", "uz": "12 kanalli elektrokardiograf" }, "price": 3500 },
    { "id": "prod-005", "model": "VS-800", "category": "medical", "image": "/Assets/vital-monitor.png", "isNew": false, "name": { "en": "Vital Sign Monitor", "ru": "Монитор пациента", "uz": "Bemor monitori" }, "description": { "en": "Multiparameter patient monitor with 12.1\" touchscreen display", "ru": "Мультипараметрический монитор пациента", "uz": "12.1\" sensorli ekranli bemor monitori" }, "price": 1200 },
    { "id": "prod-006", "model": "SR-2000", "category": "surgery", "image": "/Assets/surgical-robot.png", "isNew": true, "name": { "en": "Surgical Robot Arm", "ru": "Хирургический робот", "uz": "Jarrohlik roboti" }, "description": { "en": "Precision robotic assistance for minimally invasive procedures", "ru": "Роботизированная система для хирургии", "uz": "Minimal invaziv jarrohlik uchun robot" }, "price": "Contact for Quote" },
    { "id": "prod-007", "model": "HA-300", "category": "laboratory", "image": "/Assets/hematology-analyzer.png", "isNew": false, "name": { "en": "Hematology Analyzer", "ru": "Гематологический анализатор", "uz": "Gematologiya analizatori" }, "description": { "en": "Automated 5-part differential hematology analyzer", "ru": "Автоматический гематологический анализатор", "uz": "Avtomatlashtirilgan gematologik tahlilchi" }, "price": 8500 },
    { "id": "prod-008", "model": "EB-900", "category": "other", "image": "/Assets/icu-bed.png", "isNew": false, "name": { "en": "ICU Electric Bed", "ru": "Кровать реанимационная", "uz": "Reanimatsiya karavoti" }, "description": { "en": "Fully adjustable electric hospital bed", "ru": "Электрическая больничная кровать", "uz": "Elektr shifoxona karavoti" }, "price": 2800 },
    { "id": "prod-009", "model": "IR-50", "category": "medical", "image": "", "isNew": false, "name": { "en": "Infrared Thermometer", "ru": "Инфракрасный термометр", "uz": "Infraqizil termometr" }, "description": { "en": "Contactless clinical thermometer", "ru": "Бесконтактный термометр", "uz": "Kontaktsiz termometr" }, "price": 45 },
    { "id": "prod-010", "model": "DC-PRO", "category": "stomatology", "image": "", "isNew": true, "name": { "en": "Dental Chair Pro", "ru": "Стоматологическое кресло Про", "uz": "Stomatologik kreslo Pro" }, "description": { "en": "Electric dental chair with LED light and touchscreen control", "ru": "Электрическое стоматологическое кресло с LED-подсветкой", "uz": "LED yoritgich bilan elektr stomatologik kreslo" }, "price": 4500 }
];
